name: torch1.13_env
channels:
  - pytorch
  - https://conda.anaconda.org/nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - numpy=1.26.4
  - imageio=2.9.0
  - pip
  - pip:
      - torch==1.13.1+cu116
      - torchvision==0.14.1+cu116
      - torchaudio==0.13.1
      - --extra-index-url https://download.pytorch.org/whl/cu116
      - albumentations==1.3.0
      - blobfile==3.0.0
      - diffusers==0.31.0
      - einops==0.8.0
      - gradio==3.38.0
      - h5py==3.1.0
      - lpips==0.1.4
      - matplotlib==3.8.3
      - omegaconf==2.3.0
      - opencv-python-headless==4.8.1.78
      - pandas==2.2.1
      - pillow==9.5.0
      - protobuf==3.19.6
      - pycocotools==2.0.7
      - pyaml==23.12.0
      - scikit-learn==1.4.1.post1
      - scikit-image==0.22.0
      - scipy==1.12.0
      - seaborn==0.13.2
      - setuptools==68.2.2
      - thop==0.1.1-2209072238
      - tqdm==4.66.2
      - transformers==4.47.1
      - wandb==0.16.3

